# -- Set this if running spark jobs in a different namespace than the operator
sparkJobNamespace: "spark"

image:
  # -- Image repository
  repository: spark-operator
  # -- Image pull policy
  pullPolicy: IfNotPresent
  # -- if set, override the image tag whose default is the chart appVersion.
  tag: "latest"

uiService:
  # -- Enable UI service creation for Spark application
  enable: true

# -- Ingress URL format.
# Requires the UI service to be enabled by setting `uiService.enable` to true.
ingressUrlFormat: "{{$appName}}.localhost"

# podLabels -- Additional labels to add to the pod
podLabels: {
    user: yuriniitsuma, # just an example
  }
